version: "2"
services:
    web:
        build: .
        ports:
            - "80:80"
            - "22:22"
        volumes:
            - ./www:/var/www/localhost/htdocs
            - ./www/logs/apache2:/var/log/apache2
        links:
            - db
    db:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    cli:
        build: ./php-cli
        volumes:
            - "$VOLUMES_CLI"
        links:
            - db