version: "2"
services:
    web:
        build: .
        ports:
            - "80:8000"
        volumes:
            - ./www:/var/www/localhost/htdocs
        links:
            - db
    db:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root